apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: victoriametrics-nas
  namespace: monitoring
  labels:
    kubernetes.io/service-name: victoriametrics
    endpointslice.kubernetes.io/managed-by: homelab
addressType: IPv4
ports:
  - name: http
    port: 8428
    protocol: TCP
endpoints:
  - addresses: ["192.168.1.51"]
    conditions: { ready: true }
