apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vm-operator
  namespace: kube-system
spec:
  repo: https://victoriametrics.github.io/helm-charts/
  chart: victoria-metrics-operator
  version: 0.68.1
  targetNamespace: monitoring
  failurePolicy: abort
  valuesContent: |-
    operator:
      disable_prometheus_converter: false
      enable_converter_ownership: true
    admissionWebhooks:
      enabled: false
    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits:   { memory: 256Mi }
