apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-vmauth-public.yaml
  - cronjob-speedtest.yaml
  - deployment-vmauth-public.yaml
  - endpointslice-victoriametrics-nas.yaml
  - helm-kps.yaml
  - helm-vm-operator.yaml
  - networkpolicy-vmauth-public.yaml
  - secret-vmagent-scrape-token.yaml
  - service-victoriametrics.yaml
  - service-vmauth-public.yaml
  - vmagent-vmagent.yaml
  - vmalert-vmalert.yaml
  - vmstaticscrape-cadvisor-nas.yaml
  - vmstaticscrape-gatus-public.yaml
  - vmstaticscrape-gatus.yaml
  - vmstaticscrape-homeassistant.yaml
  - vmstaticscrape-node-exporter.yaml
  - vmstaticscrape-pgbouncer-nas.yaml
  - vmstaticscrape-postgres-nas.yaml
