apiVersion: v1
kind: Secret
metadata:
  name: vmagent-scrape-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: vmagent-vmagent
type: kubernetes.io/service-account-token
