apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  jobName: node-exporter
  targetEndpoints:
    - { targets: ["192.168.1.41:9100"], labels: { instance: aegis } }
    - { targets: ["192.168.1.49:9100"], labels: { instance: keraunos } }
    - { targets: ["192.168.1.78:9100"], labels: { instance: harpe } }
    - { targets: ["192.168.1.52:9100"], labels: { instance: bident } }
    - { targets: ["10.8.0.1:9100"], labels: { instance: trident } }
    - { targets: ["192.168.1.51:9100"], labels: { instance: kibisis } }
