apiVersion: v1
kind: ConfigMap
metadata: { name: zigbee2mqtt-seed, namespace: zigbee }
data:
  configuration.yaml: |
    version: 5
    homeassistant:
      enabled: true
    frontend:
      enabled: true
      port: 8080
    mqtt:
      base_topic: zigbee2mqtt
    serial:
      adapter: zstack
    advanced:
      channel: 20
      network_key: GENERATE
      pan_id: GENERATE
      ext_pan_id: GENERATE
      log_level: info
      log_output: [console]
