apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-backup.yaml
  - kustomization-cert-manager.yaml
  - kustomization-databases.yaml
  - kustomization-devices.yaml
  - kustomization-flux.yaml
  - kustomization-grafana.yaml
  - kustomization-kube-vip.yaml
  - kustomization-metrics.yaml
  - kustomization-nfs.yaml
  - kustomization-system-upgrade.yaml
  - kustomization-traefik.yaml
