apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 1h
  chart:
    spec:
      chart: headlamp
      version: 0.45.0
      sourceRef: { kind: HelmRepository, name: headlamp, namespace: flux-system }
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation: { retries: 3 }
  values:
    clusterRoleBinding:
      create: false

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: headlamp.lab.theoboursy.fr
          paths:
            - path: /
              type: Prefix

    resources:
      requests: { cpu: 10m, memory: 32Mi }
      limits:   { memory: 128Mi }
