apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clusterrolebinding-headlamp-admin.yaml
  - helmrelease-headlamp.yaml
  - secret-headlamp-admin-token.yaml
  - serviceaccount-headlamp-admin.yaml
