apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-manyfold.yaml
  - deployment-valkey.yaml
  - ingress-manyfold.yaml
  - pv-nfs-manyfold-models.yaml
  - pvc-models.yaml
  - service-manyfold.yaml
  - service-valkey.yaml
