apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - endpointslice-postgres-nas.yaml
  - endpointslice-postgres-public-nas.yaml
  - service-postgres.yaml
  - service-postgres-public.yaml
