apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository-homelab.yaml
  - helmrepository-csi-driver-nfs.yaml
  - helmrepository-gitea.yaml
  - helmrepository-grafana-community.yaml
  - helmrepository-headlamp.yaml
  - helmrepository-jetstack.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-victoriametrics.yaml
