apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-openwebui.yaml
  - deployment-tika.yaml
  - ingress-openwebui.yaml
  - pvc-openwebui-data.yaml
  - service-openwebui.yaml
  - service-tika.yaml
