apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-k3s-data-ro
spec:
  capacity: { storage: 400Gi }
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-ssd
  mountOptions: [nfsvers=3, hard, noatime, ro]
  csi:
    driver: nfs.csi.k8s.io
    readOnly: true
    volumeHandle: 192.168.1.51/volume2/k3s#ro
    volumeAttributes: { server: 192.168.1.51, share: /volume2/k3s }
  claimRef: { namespace: backup, name: k3s-data-ro }
