apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: k3s-data-ro, namespace: backup }
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: nfs-ssd
  volumeName: nfs-backup-k3s-data-ro
  resources: { requests: { storage: 400Gi } }
