apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.21.2
  targetNamespace: cert-manager
  failurePolicy: abort
  valuesContent: |-
    crds:
      enabled: true
      keep: true
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
    resources:
      requests: { cpu: 10m, memory: 48Mi }
      limits:   { memory: 192Mi }
    webhook:
      resources:
        requests: { cpu: 10m, memory: 24Mi }
        limits:   { memory: 96Mi }
    cainjector:
      resources:
        requests: { cpu: 10m, memory: 48Mi }
        limits:   { memory: 192Mi }
