apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-gatus.yaml
  - kustomization-gitea.yaml
  - kustomization-glance.yaml
  - kustomization-headlamp.yaml
  - kustomization-homeassistant.yaml
  - kustomization-manyfold.yaml
  - kustomization-openwebui.yaml
  - kustomization-spoolman.yaml
  - kustomization-zigbee.yaml
