apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-gitea-runner.yaml
  - helm-gitea.yaml
  - pv-nfs-gitea-data-act-runner-gitea-runner-actions-act-runner-0.yaml
  - pv-nfs-gitea-gitea-shared-storage.yaml
  - pv-nfs-gitea-valkey-data-gitea-valkey-cluster-0.yaml
  - pvc-data-act-runner-gitea-runner-actions-act-runner-0.yaml
  - pvc-gitea-shared-storage.yaml
  - pvc-valkey-data-gitea-valkey-cluster-0.yaml
