apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-act-runner-gitea-runner-actions-act-runner-0
  namespace: gitea
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-ssd
  volumeName: nfs-gitea-data-act-runner-gitea-runner-actions-act-runner-0
  resources: { requests: { storage: 1Gi } }
