apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole-system-kube-vip-role.yaml
  - clusterrolebinding-system-kube-vip-binding.yaml
  - daemonset-kube-vip-ds.yaml
  - serviceaccount-kube-vip.yaml
