apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-flux.yaml
  - provider-gitea.yaml
  - alert-gitea-commit-status.yaml
  - sources
  - k3s
  - private-hosting
  - public-hosting
