apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  chart: csi-driver-nfs
  version: 4.13.4
  targetNamespace: kube-system
  failurePolicy: abort
  valuesContent: |-
    controller:
      replicas: 1
    externalSnapshotter:
      enabled: false
